name: autoencoders
dependencies:
- ipython
- jupyter
- matplotlib
- numpy
- param
- pip
- python=3.5.1=0
- scipy
- setuptools
- pip:
  - autograd==1.1.3
  - future==0.15.2
  - holoviews==1.4.1
  - ipython-genutils==0.1.0
  - jupyter-client==4.1.1
  - jupyter-console==4.1.0
  - jupyter-core==4.0.6
  - lancet-ioam==0.9.0
  - mpld3==0.2
  - tqdm==3.7.1

